apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: server_status-to-sd
  name: server_status-to-sd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server_status-to-sd
  template:
    metadata:
      labels:
        run: server_status-to-sd
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - ./server_status_exporter --pod-name=$(POD_NAME) --namespace=$(NAMESPACE) --interval-millli-second=60
        image: springmt/rack-server-status-to-sd:v0.1.3
        name: server_status_exporter
        resources:
          requests:
            cpu: 100m
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace