apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: server_status-to-sd
  name: server_status-to-sd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server_status-to-sd
  template:
    metadata:
      labels:
        run: server_status-to-sd
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - ./server_status_exporter --metric-name=foo --metric-value=40 --use-new-resource-model --use-old-resource-model --pod-id=$(POD_ID) --pod-name=$(POD_NAME) --namespace=$(NAMESPACE)
        image: springmt/rack-server-status-to-sd:latest
        name: server_status_exporter
        resources:
          requests:
            cpu: 100m
        env:
          - name: POD_ID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.uid
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace